# Generated by Django 5.2.13 on 2026-05-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_parameterdefinition_productparametervalue_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterNumericConstraint",
            fields=[
                (
                    "parameter_definition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="core.parameterdefinition",
                    ),
                ),
                ("min_value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("max_value", models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                "db_table": "parameter_numeric_constraint",
                "managed": False,
            },
        ),
    ]
