# Generated by Django 5.2.13 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'classifier_node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('supplier', models.TextField()),
                ('weight_gram', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
