# Generated by Django 5.2.13 on 2026-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiernode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
