# Generated by Django 5.2.13 on 2026-04-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_classifiernode_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiernode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classifiernode'),
        ),
        migrations.AddField(
            model_name='product',
            name='classifier_node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classifiernode'),
            preserve_default=False,
        ),
    ]
